

backend:
  name: github
  repo: sredevopsdev/elclaustro
  branch: release
  auth_scope: repo
  open_authoring: true
publish_mode: editorial_workflow
logo_url: "https://elclaustro.cl/images/logo.svg"
locale: es
media_folder: static/images
public_folder: public/
