backend:
  name: github
  repo: sredevopsdev/elclaustro
  branch: release
  auth_scope: repo
  open_authoring: true
media_folder: static/images
publish_mode: editorial_workflow
logo_url: "https://elclaustro.cl/images/logo.svg"

        
